### PR TITLE
Detect Language API feature

### PR DESCRIPTION
**Pull request by emiroztoprak**
I implemented a language feature using Detect Language API. This API detects the languages used in the post title, description and text fields. It can also detect multiple languages, in this case the languages are stored in this format: "tr,en,fr"

### CODE REVIEW

**Review by cemkaya-mpi — CHANGES_REQUESTED** [review]
Please remove all unnecessary folders and create a request again.

**Review by MrLebowski42 — CHANGES_REQUESTED** [review]
There is a empty blog app which should be removed as we discussed in discord.

**Comment by emiroztoprak** [comment]
Okay, I removed the unnecessary blog folder.

**Review by MrLebowski42 — APPROVED** [review]
I think its good that detected languages is created as a DataField. It looks good to merge.

**Review by yunus-topal — APPROVED** [review]

**Pull request merged**
