### PR TITLE
Main app yunus

### PR DESCRIPTION
**Pull request by yunus-topal**
Since we merged muhammed branch with this branch successfully, it is time to carry on these features to MainApp.

### CODE REVIEW

**Review by MrLebowski42 — APPROVED** [review]
It looks good but is leaveCommunity html page necessary? It could be a button.

**Comment by yunus-topal** [comment]
Well, you are right but @gktpmuhammed and i talked about external apis and he might implement something with an api call on that page in the future.

**Comment by cemkaya-mpi** [comment]
I see. The only problem I see is NUM_SUGGESTIONS being commented out, which is a problem on my part. Sorry for telling you to comment it out! Turns out I actually used it in my third party api call. Let's merge. I'll fix that on the mainApp branch ASAP.

**Review by cemkaya-mpi — APPROVED** [review]

**Comment by cemkaya-mpi** [comment]
Hi @yunus-topal , I noticed that a line break was missing after the log out button in the mainapp-yunus branch. Very minor issue, but could you please add a line break after the logout button, so that the list of communities are separated from the logout button.

**Comment by cemkaya-mpi** [comment]
Another minor remark: We could display an error message upon returning an empty json as we did on other pages instead of receiving an 'IndexError at /' when the entered username and password does not exist.

**Comment by yunus-topal** [comment]
@cemkaya-mpi  okay i will make those fields required aswell.

**Comment by cemkaya-mpi** [comment]
Well, they even so, what if a nonexistent user is entered, but the fields are not empty?

**Comment by yunus-topal** [comment]
There is an errorpage.html file for it but apparently it is not working as intended. I am working on it right now

**Comment by cemkaya-mpi** [comment]
Great! Seems very good overall. Keep up the good work :+1:

**Comment by yunus-topal** [comment]
I added line break after logout and now login and error pages are working as intended. I will merge branches now.

**Pull request merged**
