### PR TITLE
Emrah

### PR DESCRIPTION
**Pull request by emrahdgn**
I have completed News API and necessary HTML files. I am merging

### CODE REVIEW

**Comment by elxif** [comment]
This pull request seems fine.

**Comment by cemkaya-mpi** [comment]
Could you please add the header to your html pages?

**Review by cemkaya-mpi — APPROVED** [review]
The code seems fine. If everything works as intended, let's merge.

**Comment by gktpmuhammed** [comment]
After these changes it seems okey, you can merge.

**Review by yunus-topal — APPROVED** [review]
It seems working fine. But instructors might want a json response instead of a normal string.

**Comment by cemkaya-mpi** [comment]
That's true. Actually, we are writing RESTful api calls [here](https://github.com/bounswe/2021SpringGroup1/issues/98). They are tested using postman. The related branch is [MainApp-RESTful](https://github.com/bounswe/2021SpringGroup1/tree/MainApp-RESTful). I believe everyone is expected to create at least one POST and GET call. If anyone hasn't done so already, please add your calls to that branch. They are currently placed in the /mainapp/external route.

**Review by MrLebowski42 — COMMENTED** [review]
There are some unnecessary files in this commit. Other than that, I don't see any issue at the first glance.

**Review by MrLebowski42 — APPROVED** [review]
It seems okay, I forgot to approve.

**Pull request merged**
