### PR TITLE
Added data sanity checks for several view functions and html templates.

### PR DESCRIPTION
**Pull request by MrLebowski42**
I added data sanity checks for view functions getCommunityTemplates, getAllPostsOfCommunity, getPost, createPost, createPostTemplates, getPostTemplates.
While it seems to be working currently, there might be several things that I missed, please review my changes.
I also added client side form validations with Javascript to createPost.html and createPostTemplate.html.

### CODE REVIEW

**Comment by cemkaya-mpi** [comment]
I looked at the changes in views.py, and they seem to be fine at first glance. For completeness' sake, could you add the navbar to the  createPost.html as well?

**Review by yunus-topal — CHANGES_REQUESTED** [review]
I checked some functionalities of the code to see if everything alright. But it seems like create post is not working at all. We need to fix that before merging

**Comment by yunus-topal** [comment]
I think it might related to changing request method. Because createPost function only works if the request method is POST.  I am not sure where this request is sent from, but if we can change its method to POSt, then everything will be fine i guess.

**Comment by yunus-topal** [comment]
You need to press "create a post" button on the community page. But İt does not gives an error on the webpage, it just doesn't response at all.

**Comment by yunus-topal** [comment]
I find another difference that might be an issue. 
In MainApp branch, when someone leaves a community,  they can go to that communities page to rejoin the community by pressing the green button that says "press to join the community". And if they click, they will get this message: "success = true"
 
But in MainApp-berke, they get this message: "success = false". Still, they can create templates for that community but probably thats because we do not whether the person is a member of that community or not.

**Comment by yunus-topal** [comment]
Well, my last comment was wrong. Join community button works fine according to communities privacy state. But people can interact with private communities even tough they are not a member. But thats okay for now.

**Comment by yunus-topal** [comment]
@MrLebowski42  this bug about creating post only occurs if community is private. There might be issue with privacy sanity checks

**Review by yunus-topal — APPROVED** [review]
I fixed the bug related to create  post and i think everything is working as intended now. We can merge this branch.

**Comment by emiroztoprak** [comment]
I think we can safely delete this branch now since we are done with the implementation and this pull request is already merged and closed.

**Pull request merged**
