### PR TITLE
Mobile system manual

### PR DESCRIPTION
**Pull request by yunus-topal**
I added mobile system manual. We can add this to master branch.

### CODE REVIEW

**Review by emrahdgn — APPROVED** [review]
I can't see any problem. There seems to be no problem with merging.

**Review by MrLebowski42 — APPROVED** [review]
Everything looks good, manual that you wrote is simple and clear. You can merge.

**Comment by gktpmuhammed** [comment]
There is no problem it is ready to merge.

**Review by gktpmuhammed — APPROVED** [review]
It is ready to merge.

**Pull request merged**
